// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBarEZZjepH3m-rtZ137OiifcqO7CCTRDI',
    appId: '1:516631954054:web:0b57f11e6e4f7bc6df0707',
    messagingSenderId: '516631954054',
    projectId: 'students-notes-app',
    authDomain: 'students-notes-app.firebaseapp.com',
    storageBucket: 'students-notes-app.appspot.com',
    measurementId: 'G-NH9YF80Y74',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJbydLi7as9MuGG0v1CPPfBsyt1RMC8Ik',
    appId: '1:516631954054:android:2e25b1d6ffbd1f3cdf0707',
    messagingSenderId: '516631954054',
    projectId: 'students-notes-app',
    storageBucket: 'students-notes-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2XxLh2xG3JNRokDE8lWoXnZvyBdiy2JQ',
    appId: '1:516631954054:ios:e25921d986f6d3c8df0707',
    messagingSenderId: '516631954054',
    projectId: 'students-notes-app',
    storageBucket: 'students-notes-app.appspot.com',
    iosBundleId: 'com.example.studentAppAdmin',
  );
}
